/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as MainCheckoutRouteImport } from './routes/_main.checkout'
import { Route as MainCatalogRouteImport } from './routes/_main.catalog'
import { Route as MainCheckoutIndexRouteImport } from './routes/_main.checkout.index'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as MainCheckoutSuccessRouteImport } from './routes/_main.checkout.success'
import { Route as MainCheckoutFailureRouteImport } from './routes/_main.checkout.failure'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MainCheckoutRoute = MainCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MainRoute,
} as any)
const MainCatalogRoute = MainCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MainRoute,
} as any)
const MainCheckoutIndexRoute = MainCheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainCheckoutRoute,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const MainCheckoutSuccessRoute = MainCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => MainCheckoutRoute,
} as any)
const MainCheckoutFailureRoute = MainCheckoutFailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => MainCheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/catalog': typeof MainCatalogRoute
  '/checkout': typeof MainCheckoutRouteWithChildren
  '/api/products': typeof ApiProductsRoute
  '/checkout/failure': typeof MainCheckoutFailureRoute
  '/checkout/success': typeof MainCheckoutSuccessRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/checkout/': typeof MainCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/catalog': typeof MainCatalogRoute
  '/api/products': typeof ApiProductsRoute
  '/': typeof MainIndexRoute
  '/checkout/failure': typeof MainCheckoutFailureRoute
  '/checkout/success': typeof MainCheckoutSuccessRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/checkout': typeof MainCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/catalog': typeof MainCatalogRoute
  '/_main/checkout': typeof MainCheckoutRouteWithChildren
  '/api/products': typeof ApiProductsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/checkout/failure': typeof MainCheckoutFailureRoute
  '/_main/checkout/success': typeof MainCheckoutSuccessRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/_main/checkout/': typeof MainCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/checkout'
    | '/api/products'
    | '/checkout/failure'
    | '/checkout/success'
    | '/api/telegram/webhook'
    | '/checkout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catalog'
    | '/api/products'
    | '/'
    | '/checkout/failure'
    | '/checkout/success'
    | '/api/telegram/webhook'
    | '/checkout'
  id:
    | '__root__'
    | '/_main'
    | '/_main/catalog'
    | '/_main/checkout'
    | '/api/products'
    | '/_main/'
    | '/_main/checkout/failure'
    | '/_main/checkout/success'
    | '/api/telegram/webhook'
    | '/_main/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ApiProductsRoute: typeof ApiProductsRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/checkout': {
      id: '/_main/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof MainCheckoutRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/catalog': {
      id: '/_main/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof MainCatalogRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/checkout/': {
      id: '/_main/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof MainCheckoutIndexRouteImport
      parentRoute: typeof MainCheckoutRoute
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/checkout/success': {
      id: '/_main/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof MainCheckoutSuccessRouteImport
      parentRoute: typeof MainCheckoutRoute
    }
    '/_main/checkout/failure': {
      id: '/_main/checkout/failure'
      path: '/failure'
      fullPath: '/checkout/failure'
      preLoaderRoute: typeof MainCheckoutFailureRouteImport
      parentRoute: typeof MainCheckoutRoute
    }
  }
}

interface MainCheckoutRouteChildren {
  MainCheckoutFailureRoute: typeof MainCheckoutFailureRoute
  MainCheckoutSuccessRoute: typeof MainCheckoutSuccessRoute
  MainCheckoutIndexRoute: typeof MainCheckoutIndexRoute
}

const MainCheckoutRouteChildren: MainCheckoutRouteChildren = {
  MainCheckoutFailureRoute: MainCheckoutFailureRoute,
  MainCheckoutSuccessRoute: MainCheckoutSuccessRoute,
  MainCheckoutIndexRoute: MainCheckoutIndexRoute,
}

const MainCheckoutRouteWithChildren = MainCheckoutRoute._addFileChildren(
  MainCheckoutRouteChildren,
)

interface MainRouteChildren {
  MainCatalogRoute: typeof MainCatalogRoute
  MainCheckoutRoute: typeof MainCheckoutRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCatalogRoute: MainCatalogRoute,
  MainCheckoutRoute: MainCheckoutRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ApiProductsRoute: ApiProductsRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
